#+TITLE: Macports Usage Info & Info On The Setup of Selected Ports

* The setup process for selected ports
** MySQL
*** Set-up
You can use select to create symlinks in =/opt/local/bin= to the commands in =/opt/local/lib/mysql55/bin/=

This allows you to avoid having to use the version suffixed commands (e.g. =mysql5=), creating your own symlinks or adding that directory to your path.

: sudo port install mysql55-server
possibly also need
: sudo port install mysql55
and then
: sudo port install mysql_select
and then 
: sudo port select --set mysql mysql55

The default user/owner of mysql is =_mysql= so then we run
: sudo -u _mysql /opt/local/lib/mysql55/bin/mysql_install_db
or if you have run "port select"
: sudo -u _mysql mysql_install_db
That gives the output (that may be useful for later):

#+BEGIN_VERSE
Password:
Installing MySQL system tables...
OK
Filling help tables...
OK

To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system

PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER !
To do so, start the server, then issue the following commands:

/opt/local/lib/mysql55/bin/mysqladmin -u root password 'new-password'
/opt/local/lib/mysql55/bin/mysqladmin -u root -h AirBook.local password 'new-password'

Alternatively you can run:
/opt/local/lib/mysql55/bin/mysql_secure_installation

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the manual for more instructions.

You can start the MySQL daemon with:
cd /opt/local ; /opt/local/lib/mysql55/bin/mysqld_safe &

You can test the MySQL daemon with mysql-test-run.pl
cd /opt/local/mysql-test ; perl mysql-test-run.pl

Please report any problems with the /opt/local/lib/mysql55/bin/mysqlbug script!
#+END_VERSE
*** Starting MySQL Server
: sudo mysqld_safe
** Postgres
** MongoDB
See [[*MongoDB][Starting MongoDB]]
* Starting Some Macports Installed Processes
** MongoDB
: sudo mongod --dbpath /opt/local/var/db/mongodb
