#+TITLE: Help for all Unix Related Things

*Other Org-Mode files with relevant info*
 - See [[file:Mac%20Use%20of%20Unix.org][UNIX tips specific to OS X]] for mac related differences
 - See [[file:Shell%20Scripting%20Magic.org][Shell Scripting Docs]] for some cool shell scripting commands and things that often trip me up
 -  Also see [[file:Z-Shell.org][Z-Shell]] setup, tips and tricks
 - See [[file:psql%20commands.org][Postgres & psql]] for some more advice on that area (mostly psql atm)
 - See [[file:my%20emacs%20and%20keybinding%20dilemma.org][The Emacs/Linux/Super Key epic keybinding Odyssey.org]] for more info on changing keybindings in Linux
 - See [[file:Git%20Usage%20Notes.org][Git Usage Notes]] for info on GIT usage
 - See [[file:Catalyst%20Related/Catalyst%20Related%20Tasks%20&%20Info.org][Catalyst Related Tasks & Info]] for stuff that was more specific to Catalyst Than Not
   - Covers
     - linux
     - Moodle
     - Drupal


* Using Google Drive and User Permissions across various machines
** I thought I had a problem because of user permissions
Things in Google Drive are owned by the User of the machine that added them
for example most things from BigMac are
|--------+-------|
| User   | Group |
|--------+-------|
| Noches | staff |
|--------+-------|

whereas on AirBook most things are 
|------+-------|
| User | Group |
|------+-------|
| Hal  | staff |
|------+-------|

Now by default on both machines the memebership of the staff group is

: BigMac:Google Drive Noches$ dscl . read /Groups/staff GroupMembership
: GroupMembership: root

 - So on the other machine we are not that user, and we arent in that group.
 - Therefore we are now dependent on the world read, write, execute permissions...
   - In particular the world execute permissions?
     - This file is not viewable on the other machine:
: -rw-r--r--@  1 Noches  staff  103306 Feb 23  2012 Hal Henke - Post esuite Resume.pages
Even doing
: sudo ls -la
I cant see anything in this directory!

Hmmm Perhaps Directories i can read/access have a @ sign after their permissions?
: drwxr-xr-x  30 Hal  staff    1020 14 Jan 21:21 .
: drwxr-xr-x@ 14 Hal  staff     476 14 Jan 21:13 ..

Or the file does\\ 
when I view in Airbook:
: -rw-r--r--@  1 Hal  staff   192116 29 Dec 03:38 Thor379017_zps3bda02da.jpg
Same file from BigMac:
: -rw-------   1 Noches  staff   192116 Dec 29 03:38 Thor379017_zps3bda02da.jpg

** But i think that was just that Google Drive didnt finish syncing properly
** Using as a git repository?
See here: [[file:Git%20Usage%20Notes.org::*Setting%20up%20a%20git%20repo%20in%20Google%20Drive][Setting up a git repo in Google Drive?]]


* Desktop Configuration
Use:
: $ dconf-editor
to change many hidden/non-obvious settings in Linux\/Debian\/Ubuntu
Also: 
Settings->Keyboard->Shortcut
AND
Settings->Keyboard Layout
for various weird things

* Quickly add your .inputrc file to another server
From ~ directory
=scp .inputrc krb01.catalyst-au.net:=
* Package Management
** dpkg and subsidiary/related commands
*dpkg*
 - dpkg-deb
 - dpkg-query
 - dselect
 - deb
 - deb-control
 - dpkg.cfg
 - dpkg-reconfigure

** Update Package List
: apt-get update
** Where are package archives stored (.deb files)
: /var/cache/apt/archives
** Search for package
e.g. port search package
: apt-cache search package
OR to match against/search only the package names
: apt-cache search -n package
** Info on package
e.g. port info package
: apt-cache show package
or more detail
: apt-cache showpkg package
** Package Dependencies
: apt-cache depends sbcl
** Show installed packages
e.g. port installed | grep python
: dpkg --get-selections | grep python
OR
: dpkg -l
** Show available packages
: apt-cache pkgnames
** Show which version of a package is installed
e.g. port installed | grep python
: dpkg -l | grep package
** Show which packages a package needs that arent yet installed
i.e. combo of 
: apt-cache depends sbcl
and check to see if each is installed
I think this is equiv to 
: port unmet sbcl

The crazy thing is we can easily do the opposite
:  apt-cache --recurse --installed depends sbcl
With some effort we can get
: apt-cache --recurse depends  emacs | grep Depends | sed 's_.*Depends: __' | xargs dpkg --status| grep Status
** Show which package dependecies our SYSTEM currently has unfulfilled
Nothe this prints for *all packages*
: apt-cache unmet 
** Show where files from a package are installed
: dpkg-query -L bash-completion
** Reconfigure package
: dpkg-reconfigure packagename
** Show Contents of a package
*** A package in the cache
use apt-file
: apt-file pkg_name
 - (probably needs to be installed and updated)
*** A  local .deb package 
: dpkg-deb -c package.deb
** Show changelog for a package (installed)
: apt-listchanges pkg_name
or (*This seems like a bit of a bitch*)
: cat /usr/share/doc/somepackage/changelog.Debian.gz
** Adding a package ppa with add-apt-repository 
The following line will add a file in directory =/etc/apt/sources.list.d/=:
: sudo add-apt-repository ppa:doctormo/wacom-plus
The resulting file is: 
#+BEGIN_SRC bash
hal@HAL9000:~/work/test-sites/my-moodle-23$ cat /etc/apt/sources.list.d/doctormo-wacom-plus-precise.list 
deb http://ppa.launchpad.net/doctormo/wacom-plus/ubuntu precise main
deb-src http://ppa.launchpad.net/doctormo/wacom-plus/ubuntu precise main
#+END_SRC
** Getting a list of packages line by line only
: apt-cache --recurse depends  emacs | grep Depends | sed 's_.*Depends: __'
OK Assuming we have a deb package locally we can get the top level depends via
: dpkg --info ../emacs24-lucid_24.2+1-2_amd64.deb | grep Depends | sed -e 's_, _\n_g' | sed -e 's_(.*)__' | sed -e 's_ Depends: __'
** Using apt-tools when you dont have root access/installing in a local directory
Quite difficult
*** Use dpkg to manually install package where you want
: dpkg -i --force-not-root --root=$HOME package.deb
**** Probems
I created a directory 
: ~/local
and a variable
: HAL_ROOT=$(pwd)
then the comand:
: dpkg --force-not-root --root=$HAL_ROOT -i deb-packages/emacs24-lucid_24.2+1-2_amd64.deb
 First I needed to copy recursively the directory with all dpkg info
: /var/lib/dpkg/
to
: ~/local/var/lib/dpkg/

But the problem is 
#+BEGIN_VERSE
 error setting ownership of `./usr': Operation not permitted
dpkg-deb: subprocess paste killed by signal (Broken pipe)
dpkg (subprocess): failed to chroot to `/home/hal.henke/local': Operation not permitted
#+END_VERSE
Apparently we need chroot for this method to work and chroot needs sudo.
*** Download source files of package and configure them manually to install locally
#+BEGIN_SRC shell
apt-get source package
cd package
./configure --prefix=$HOME
make
make install
#+END_SRC
*** Use dpkg this to extract package where you want?
: dpkg -X 
Think this is the same as
: dpkg-deb -x /path/to/some.deb $HOME
*** Setup a virtual root directory with chroot/schroot
Kind of requires root privileges at least once
*** Use an alternative package manager such as Nix-OS
**** Nix-OS
2,500 packages
http://nixos.org/
**** JHBuild
https://live.gnome.org/Jhbuild
**** Zero Install
http://0install.net/
**** Package Source
 - 12000 packages
 - Installs from source but manages dependecies apparently
http://www.pkgsrc.org/
*** A combination of ways
We need to
 - get the unmet dependencies of a package
 - get the deb files
 - install locally


**** Attempts to automatically check unmet dependencies

**** Force apt-cache to temporarily use an additional cache without sudo?
Problem is that we cant use apt-cache to locate dependencies that arent installed already if we use a .deb package that we dont get from our archives
**** Getting packages and installing locally
Get the URLS of the packages
: apt-get -y install --print-uris emacs | cut -d\' -f2 | grep http:// > apturls
Get everything in that file
: wget -i path-to-apturls-file
Install locally (into "sub-root")
: dpkg -x emacs24-lucid_24.2+1-2_amd64.deb sub-root/

Set the dynamic library path
: export LD_LIBRARY_PATH="/home/hal.henke/local/sub-root/usr/lib"

* Using pkgsrc
Download and compile with the unprivileged flag so we can install in our own directories

A good description of bilding from source/unprivileged
http://leaf.dragonflybsd.org/~justin/handbook/pkgsrc-sourcetree-using.html
** How to install a package
Change to the package directory
: cd ~/local/pkgsrc/editors/emacs
Build pakagae
: bmake
Install
: bmake install
** Remove package
: bmake deinstall
** Update package
: bmake update
or 
: bmake replace
or to update all that need updating from source
: pkg_chk -u -s
** Getting pkg-vulnerabilities
: /home/hal.henke/pkg/sbin/pkg_admin -K /home/hal.henke/pkg/var/db/pkg fetch-pkg-vulnerabilities
** Adding to your PATH
Add the pkgsrc commands, man pages for their use and the commands installed by pkgsrc.

#+BEGIN_SRC shell-script
# Add pkgsrc commands - after regular commands
PATH=$PATH:$HOME/pkg/sbin:$HOME/pkg/bin
MANPATH=:$HOME/pkg/man
#+END_SRC
** Showing build options avilable
From the directory of the package you are building:
: bmake show-options
** Changing options
pkgsrc is going to look in a global configuration file called mk.conf
example change - To enable mysql on builds of postfix 
: echo "PKG_OPTIONS.postfix+=mysql" >> ~/pkg/etc/mk.conf
*** Where is mk.conf
The location is
: ${PREFIX}/etc/mk.conf
or 
: /usr/etc/mk.conf
if installed globally

If you installed as unprivileged then 
: PREFIX=~/pkg
by default, so we are looking at 
: ~/pkg/etc/mk.conf
*** Changing options
First see default options.
From package src drirectory:
: bmake show-options
Add the following line to 
: ~/pkg/etc/mk.conf
Make sure you add this between the "if" flags - otherwise seems to be ignored...
: PKG_OPTIONS.emacs=    motif -gtk
We can see which options are supported by looking in the
: options.mk
file in the pkg directory and this will also tell us the name of the package to use in
: PKG_OPTIONS.package_name
*** Emacs specific version
If using the "emacs" metapackage you have to set the env variable EMACS_TYPE
: export EMACS_TYPE="emacs24"
Must do this before installing and deinstalling - otherwise pkgsrc will 
choose emacs23 by default.
** PROBLEMS with installing emacs
*** Canberra-GTK-module
It would crash with 
#+BEGIN_VERSE
Gtk-Message: Failed to load module "canberra-gtk-module"

(emacs-23-4:31007): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderFc', script='latin'
Connection lost to X server `:1022.0'
When compiled with GTK, Emacs cannot recover from X disconnects.
This is a GTK bug: https://bugzilla.gnome.org/show_bug.cgi?id=85715
For details, see etc/PROBLEMS.
Fatal error (6)
#+END_VERSE
The problem seems to be that the variable 
: GTK_MODULES 
has the value
: canberra-gtk-module
so install that:
#+BEGIN_VERSE
cd local/pkgsrc/audio/libcanberra
bmake
bmake install
#+END_VERSE
*** No fonts
http://mail-index.netbsd.org/pkgsrc-users/2011/07/20/msg014714.html

I installed both
: local/pkgsrc/fonts/font-misc-misc
and
: local/pkgsrc/fonts/font-misc-misc
: local/pkgsrc/fonts/urw-fonts/
*** Emacs can't find x-server and crashes
Can start in a terminal with 
: emacs -nw
or start a daemon
: emacs --daemon
* Using nix-pkg
: ./configure  --prefix=$HOME/hal-nix/local/ --with-store-dir=$HOME/hal-nix/store/ --localstatedir=$HOME/hal-nix/var/

: The Perl modules DBI and/or DBD::SQLite are missing 

* Setting up/Installing emacs24 when only emacs23 is in the apt-cache package repository
First get all the dependencies of emacs 23 and then i think i just installed 24 to /usr/local

Alternatively this guy has a repository where he has snapshots of later builds
#+BEGIN_SRC bash
sudo add-apt-repository ppa:cassou/emacs
sudo apt-get update
sudo apt-get install emacs-snapshot
emacs-snapshot
#+END_SRC bash


* Editing files on remote machines from EMACS via TRAMP

Emacs will work the same on remote machines as when you are editing a file as root on the local machine.
As long as the hostname is in /etc/hosts and the machine unnderstands the scpc protocol 
(means you can do stuff without constantly using password as in scp) then you go
C-x C-f /user@host:/path/to/file

*Important* - You will probably be asked for your passphrase as well as/instead of the password
Make sure you dont muck this up too much as you wont get in!


* Editing files as root or another user on the local machine using TRAMP

Slightly different syntax here
: C-x C-f /sudo:root@localhost:/path/to/whatever
or just:
: C-x C-f /sudo:hal@localhost:/path/to/whatever

* scp doesn't work if your .bashrc_local or other files produce output
You will have to remove any messages such as 
echo "bash_profile called..."
or anything that causes errors because a $TERM is not defined.
Perhaps can put them in conditional blocks

See:
http://www.unix.com/aix/136087-scp-not-working-while-ssh-works.html
http://apple.stackexchange.com/questions/13802/why-does-echo-in-etc-bashrc-cause-scp-to-hang

Might have to think more carefullly about what i put in each script - login/interactive etc

* Dont Plug your iPhone into USB *WITH PERSONAL HOTSPOT ENABLED*

It would add weird connectors to ifconfig
i.e. i had more than just eth0 and lo
(which is what i should have)
i.e. type
=$ ifconfig=
and you'll get something like:
** eth0      Link encap:Ethernet  HWaddr 54:e6:fc:84:f9:20  
          inet addr:192.168.124.169  Bcast:192.168.125.255  Mask:255.255.254.0
          inet6 addr: fe80::56e6:fcff:fe84:f920/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4849688 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3749770 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3335296075 (3.3 GB)  TX bytes:1329359683 (1.3 GB)
          Interrupt:16 Base address:0xe000 

** eth1      Link encap:Ethernet  HWaddr 6c:62:6d:3a:87:f3  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:52 Base address:0x4000 

** eth2      Link encap:Ethernet  HWaddr 7e:c5:37:73:52:f6  
          inet addr:172.20.10.4  Bcast:172.20.10.15  Mask:255.255.255.240
          inet6 addr: fe80::7cc5:37ff:fe73:52f6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1573 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1915 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:919187 (919.1 KB)  TX bytes:271977 (271.9 KB)

** lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:188718 errors:0 dropped:0 overruns:0 frame:0
          TX packets:188718 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:71600564 (71.6 MB)  TX bytes:71600564 (71.6 MB)

** When you should have just eth0 and lo

** Getting rid of them
=sudo ifconfig eth1 down=

** AMMENDED - seems harmless...
...as long as Personal Hotspot is not enabled

* Things I learned Trying to Speed up KDE

** How to restart kwin

Press
Alt+F2
Type
kwin --replace&
cick run

** How to restart Xorg (without logging out)
$ sudo service gdm restart

** $ free -m
total       used       free     shared    buffers     cached
Mem:          7967       6094       1873          0         62        936
-/+ buffers/cache:       5095       2872
Swap:         8170          0       8170


** Turn the swap off
$ sudo swapoff -a
and on
$ sudo swapon -a

** Look at the "swappiness"
$ cat /proc/sys/vm/swappiness 

** See here:
http://forum.kde.org/viewtopic.php?f=66&t=85803
We edit the system file:
/etc/sysctl.conf
adding the following lines:
# HAL - trying to make KDE snappier
vm.swappiness=20
vm.vfs_cache_pressure=50

** This thread is the greatest:
http://forum.kde.org/viewtopic.php?f=66&t=85803&sid=ee5334e50b6b877d1b5e644b07f355ad&start=15
possible causes:
 - akonadiserver / akonadi processes 
 - Fixing the application which excessively spawns kio_trash would help also. 
Grepping ~/.xsession-errors for " Killing update job for "trash:/"" may help reveal the culprit, with the KIO debugging area enabled. KRunner does this intensively.
 - Nepomuk 
 - the Oxygen widget style

** Dealing With Akonadi
The Akonadi server is launched automatically at login whenever any Akonadi-enabled application requests access to it.

To disable the Akonadi subsystem, first, shut down the running Akonadi server from the control module or the command line:

: akonadictl stop
Now, edit the file ~/.config/akonadi/akonadiserverrc and change StartServer from true to false:

StartServer=false
The Akonadi server should no longer launch automatically on login.

** A useful tool to accurately show memory growth over time
exmap

** Scripts for investigating memory problems:
-----------------------------------------------------------------------------
#!/bin/sh

printf "%-6s %-9s %s\n" "PID" "Total" "Command"
printf "%-6s %-9s %s\n" "---" "-----" "-------"

for PID in `ps -e | /usr/bin/awk '$1 ~ /[0-9]+/ { print $1 }'`
do
CMD=`ps -o comm -p $PID | tail -1`
# Avoid "pmap: cannot examine 0: system process"-type errors
# by redirecting STDERR to /dev/null
TOTAL=`pmap $PID 2>/dev/null | tail -1 | \
/usr/bin/awk '{ print $2 }'`
[ -n "$TOTAL" ] && printf "%-6s %-9s %s\n" "$PID" "$TOTAL" "$CMD"
done | sort -n -k2 
-----------------------------------------------------------------------------
This little one liner is also good for snapshotting i.e. execute this at a particularly laggy moment if possible:
$ ps -eo pcpu,%mem,cmd|sort -k2 -r


** Latest Findings
I set my swappiness to 20 and rebooted. Everything was fine for a couple of days even but now its back:
High Xorg and Kwin usage
NO SWAP though

I deleted delete the folder /tmp/kde-hal/
 - NOTHING happened.
I deleted the folder /var/tmp/kdecache-hal
 - maybe some change but pretty slight....
 xorg and kwin still churning

** Pretty sure its the NVIDIA/ drivers that are behind it all

http://forum.kde.org/viewtopic.php?f=66&t=94861

From here:
http://askubuntu.com/a/23238/how-can-i-find-what-video-driver-is-in-use-on-my-system
#+BEGIN_VERSE
$ jockey-text -l
xorg:nvidia_current - NVIDIA accelerated graphics driver (Proprietary, Enabled, In use)
xorg:nvidia_current_updates - NVIDIA accelerated graphics driver (post-release updates) (Proprietary, Disabled, Not in use)
xorg:nvidia_experimental_304 - NVIDIA accelerated graphics driver (**experimental** beta) (Proprietary, Disabled, Not in use)
xorg:nvidia_experimental_310 - NVIDIA accelerated graphics driver (**experimental** beta) (Proprietary, Disabled, Not in use)
#+END_VERSE

or
#+BEGIN_VERSE
$ sudo lshw -c video
  *-display               
       description: VGA compatible controller
       product: GF108 [GeForce GT 440]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:16 memory:fa000000-faffffff memory:d0000000-d7ffffff memory:d8000000-d9ffffff ioport:e000(size=128) memory:fb000000-fb07ffff
#+END_VERSE

#+BEGIN_VERSE
$ sudo modinfo nvidia
ERROR: modinfo: could not find module nvidia
#+END_VERSE

#+BEGIN_VERSE
$ dpkg -l | grep nvidia
ii  libkwinnvidiahack4                     4:4.8.5-0ubuntu0.1                      library used by nvidia cards for the KDE window manager
ii  nvidia-common                          1:0.2.44.2                              Find obsolete NVIDIA drivers
ii  nvidia-current                         295.40-0ubuntu1.1                       NVIDIA binary Xorg driver, kernel module and VDPAU library
ii  nvidia-settings                        295.33-0ubuntu1                         Tool of configuring the NVIDIA graphics driver
#+END_VERSE

** NVIDIA X Server Settings
NVIDIA Driver Version: 295.40
Server Version: 11.0

Graphics Card/GPU: GeForce GT 440

** Can reset swap/memory configuration at runtime
using sysctl
$ sysctl swappiness=10

** Another Cool thread
http://forum.kde.org/viewtopic.php?f=66&t=97736

** Other Stuff
http://pthreads.blogspot.com.au/2011/12/swappiness-and-dropcaches.html
To free pagecache:
=code=
echo 1 > /proc/sys/vm/drop_caches
=code=
To free dentries and inodes:
=code=
echo 2 > /proc/sys/vm/drop_caches
=code=
To free pagecache, dentries and inodes:
=code=
echo 3 > /proc/sys/vm/drop_caches
=code=

** Arch_Linux on Performance
https://wiki.archlinux.org/index.php/Maximizing_Performance

** I'm going to install driconf
Its something for tuning Graphics Card Performance...
"Enabling HyperZ can drastically improve performance"
sudo apt-get driconf

** Latest Attempts to improve NVIDIA
I mucked around with nvidia-settings and nvidia-xconfig - didnt seem to do anything...
I then aded the following to the end of my 
/etc/X11/xorg.conf 
#+BEGIN_SRC conf-mode
Section "Module"
    Load "dbe"
    Load "extmod"
    Load "type1"
    Load "freetype"
    Load "glx"
EndSection
#+END_SRC conf-mode
based on advie from:
# http://forum.kde.org/viewtopic.php?f=66&t=94861


* Network speed
Not sure why but sometimes very slow and 
=ifconfig=
reveals
something like
#+BEGIN_SRC 
eth0      Link encap:Ethernet  HWaddr 54:e6:fc:84:f9:20  
          inet addr:192.168.124.169  Bcast:192.168.125.255  Mask:255.255.254.0
          inet6 addr: fe80::56e6:fcff:fe84:f920/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5355706 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4124872 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3750265994 (3.7 GB)  TX bytes:1365421940 (1.3 GB)
          Interrupt:16 Base address:0xe000 

eth1      Link encap:Ethernet  HWaddr 6c:62:6d:3a:87:f3  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:52 Base address:0x4000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:243000 errors:0 dropped:0 overruns:0 frame:0
          TX packets:243000 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:89351225 (89.3 MB)  TX bytes:89351225 (89.3 MB)
#+END_SRC 

when there should only be eth0 & lo
In this case do:
=sudo ifconfig eth1 down=
to get rid of one of them...

* Changing my machine name
: sudo edit /etc/hostname
and replaced 
=catalyst-MS-7681=
with 
=HAL9000=

also see 
: man hostname
for related info

* Checking my distro version
: $ cat /etc/issue

Also, this:
: $ uname -r
does something - not sure what

* Checking Hardware Drivers etc
** lshw
_List Hardware_
** jockey-text
_Text version of the Program Jockey_
: sudo jockey-text -l 
will list drivers and enabled/disabled status
sudo jockey-text -e xorg:nvidia-185
will enable the xorg:nvidia-185 driver
** modinfo
_Show info about a linux kernel module_
Or look at /lib/modules

** lsmod
_Show the status of modules/drivers_


* Upgrading NVIDIA drivers
http://www.itworld.com/software/289579/install-nvidia-driver-30432-linux-mint-13-or-ubuntu-12041210
#+BEGIN_SRC
sudo apt-add-repository ppa:xorg-edgers/ppa
sudo apt-get update
sudo apt-get install nvidia-current nvidia-settings
#+END_SRC
Latest from NVIDIA site - 310.19
One currently installed in my system - 295.40-0ubuntu1.1
  
* Setting up VirtualBox
Get an iso disk image of the requested distribution

They were found on caldara:
scp caldara:/home/shared/isos/ubuntu-10.04-server-amd64.iso .

** Tried to copy from Daniel
I reinitialized the mac adress - this meant that the virtual machine thought a new PCI Card had ben put in and so it reassigned it to eth2 or something

*** fstab
Used to setup the link to my physical machine i think - we mount a directory as a file system

*** /etc/sudoer ?
Something that gave me permission to do stuff
hal ALL = NOPASSWD:ALL

** Network stuff
Add self to =/etc/sudoers=
Will have to install openssh-server
: $ sudo apt-get install openssh-server

Get your IP address from ifconfig
Then you can scp from one machine to the other by
: $ scp file user@ipadress:path
or by adding their ipaddress to the local machines /etc/hosts file
with
: $ ipadress HAL9000
: $ scp /etc/sudoers hal@HAL9000:/home/hal/work/rails/hurricane/dans_machine_settings/etc/
This works both ways: you get their ip through ifconfig and add it to your hosts file and you can
scp the other way.


* TKS

Run 
tks -t week > 2012-11-12.tks
To get a file with a template for the current week
or 
tks -t month > filename.tks
to get the current month
tks filename.tks
will tell you problems without commmitting while:
tks -c filename.tks
will commit your file to the server.




http://rubyenterpriseedition.googlecode.com/files/ruby-enterprise_1.8.7-2012.02_amd64_ubuntu10.04.deb
http://rubyforge.org/frs/download.php/66163/ruby-enterprise_1.8.7-2009.10_amd64.deb


* SSH Stuff
** Adding my passphrase to my ssh shell settings
used the command 
: ssh-add
To make this work when you log into other machines I did ssh-add and then
we created a file 
: ~/.ssh/config
that contained the following
#+BEGIN_SRC 
host *
   2     forwardAgent yes
#+END_SRC 
** Getting ssh to forward your keys
: shh -A you@wherever
** Being able to launch graphical X programs from another machine on your local machine
: shh -X you@wherever

** Removing a key from your known_hosts file
e.g. for caldara:
ssh-keygen -f "/home/hal/.ssh/known_hosts" -R caldara

** Have the right permissions on your private key (=.ssh/id_rsa=)
e.g. private key in particular should be
: -rw-------   1 Hal  staff   1679 17 Jan 22:01 id_rsa

The following should fix most probs
#+BEGIN_SRC bash
chmod 700 ~/.ssh
chmod 600 ~/.ssh/id_rsa
chmod 644 ~/.ssh/id_rsa.pub  
chmod 644 ~/.ssh/authorized_keys
chmod 644 ~/.ssh/known_hosts
#+END_SRC


* DONE Fucking annoying command line error in Konsole - FIXEDish

Sometimes when i go back through history via up arrow part of the command gets "stuck" on the command line e.g.
scp  mynbcs-rails201
git remote add publi

interesting that its the same number of characters.
Due to .inputrc?
Fiddling with prompt in .bashrc_local?
Changing key commands in Konsole shortcuts?

** SOLUTION
Seems it had something to dow with my attempts to modify my prompt with colours and escape sequences 
and shit that was probably not quite done properly



* Extract a password from a password_tmp.txt file
$ gpg -d pasword_tmp.txt

* Generate a password
=$ pwgen=

* Building a debian package
** Fucking up the version number and having to fix it
Just say the version number doesnt bump

Then edit the debian/changelog file and manually change the version number e.g.
from
moodle-site-greenmedicine (1.9.19.20120702-1ubuntu1) precise; urgency=low
to
moodle-site-greenmedicine (1.9.20.20120702-1ubuntu1) precise; urgency=low




* SSH & git valid paths
From stackoverflow:
A valid ssh URL should look like ssh://{user}@host.xz/path/to/repo.git 
[[http://oliver.net.au/?p=174][Git remote ssh syAZ9ERLzpF991ntax]]
The ‘git remote add’ command takes in a html URL like parameter for even SSH like:
: ssh://<user>@<host>/<path to git repo>/

NOT the standard ssh scp syntax:
: ssh://<user>@<host>:<path to repo>/

* HTTP basic Auth
Seems to be something that prevents you accessing a web page without authorisation in the 
header request i.e. before a login page or anything
http://en.wikipedia.org/wiki/Basic_access_authentication

* The sudoers file
: root ALL=(ALL) ALL
This line means: The root user can execute from ALL terminals, acting as ALL (any) users, and run ALL (any) command.
: hal     ALL=NOPASSWD: ALL
Means you wont be asked for a password either....
http://www.garron.me/linux/visudo-command-sudoers-file-sudo-default-editor.html

* Adding someone to sudoers group/file
you can edit =/etc/sudoers= file
or do:
: visudo
which does that directly

* Changing someones group membership
As root - adding me to group admin
: su root
: usermod -aG admin hal

* Proxies and FoxyProxy
Check all connections etc with 
sudo netstat -anp | more

With =OS X= its different - use =lsof= ?



* Konsole
** Keybindings
Go To Configure Current Profile -> Input and then
edit the current input list
You can bind keys to pretty much any escape sequence....
e.g.
*** PageUp
=Page Up -> \E[5~= 
to 
=Page Up -> ScrollPageUp=
and
=Page Down -> \E[6~=
to 
=Page Down -> ScrollPageDown=
*However*
Then PageUp and Down dont function interchangably with f & b when in man page etc





















